services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Crowdin\:
    resource: '../Classes/*'
    # glob for services that have been previously available as
    # container entries and have been removed in the mean time
    # (e.g. because factories are to be used instead)
    exclude: '../Classes/{Xclass/LanguageServiceXclassed.php}'

  GeorgRinger\Crowdin\EventListener\AfterPackageActivation:
    tags:
      - name: event.listener
        identifier: 'core-afterpackageactivation-crowdin'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent

  GeorgRinger\Crowdin\EventListener\AfterPackageDeactivation:
    tags:
      - name: event.listener
        identifier: 'core-afterpackagedeactivation-crowdin'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent

  GeorgRinger\Crowdin\Command\EnableCommand:
    tags:
      - name: 'console.command'
        command: 'crowdin:enable'
        schedulable: false
        description: 'Enable Crowdin'

  GeorgRinger\Crowdin\Command\DisableCommand:
    tags:
      - name: 'console.command'
        command: 'crowdin:disable'
        schedulable: false
        description: 'Disable Crowdin'

  GeorgRinger\Crowdin\Xclass\LanguageServiceFactoryXclassed:
    public: true
    arguments:
      $runtimeCache: '@cache.runtime'

  cache.runtime:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['runtime']
