services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  GeorgRinger\Crowdin\:
    resource: '../Classes/*'

  GeorgRinger\Crowdin\EventListener\AfterPackageActivation:
    tags:
      - name: event.listener
        identifier: 'core-afterpackageactivation-crowdin'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent

  GeorgRinger\Crowdin\EventListener\AfterPackageDeactivation:
    tags:
      - name: event.listener
        identifier: 'core-afterpackagedeactivation-crowdin'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent

  GeorgRinger\Crowdin\Command\EnableCommand:
    tags:
      - name: 'console.command'
        command: 'crowdin:enable'
        schedulable: false
        description: 'Enable Crowdin'

  GeorgRinger\Crowdin\Command\DisableCommand:
    tags:
      - name: 'console.command'
        command: 'crowdin:disable'
        schedulable: false
        description: 'Disable Crowdin'
